### PR TITLE
updated windows configuration

### PR DESCRIPTION
**Pull request by dmc6297**
Used ; instead of && to run multiple commands
Had to use an absolute path to the x64 emulator

### CODE REVIEW

**Comment by Esshahn** [comment]
great! thanks for helping out. Is everything else working on Windows?

**Comment by Esshahn** [comment]
had to revert the change as it wasn't the right syntax with ";"

**Comment by dmc6297** [comment]
Ok, however the && syntax does not work, where the ; did

**Comment by Esshahn** [comment]
Interesting... could be related to the windows version maybe. I'm using a VM with win 7 and 8, I assume you have a way newer version?

**Pull request merged**
